const modules = [
  { name: "Users" },
  { name: "Employees" },
  { name: "Roles & Permissions" },
  { name: "Roles" },
  { name: "Permissions" },
  { name: "Leads" },
  { name: "List" },
  { name: "Customers" },
  { name: "Bank Details" },
  { name: "Power of Attorney" },
  { name: "Properties" },
  { name: "All Units" },
  { name: "Community Name" },
  { name: "Project Name" },
  { name: "Building Name" },
  { name: "Sub Type" },
  { name: "Developer Name" },
  { name: "Amenities Name" },
  { name: "Availablity Sheet" },
  { name: "Sale Offer" },
  { name: "Managements" },
  { name: "Overview" },
  { name: "Managements" },
  { name: "PM Invoices" },
  { name: "Tenancy Contract" },
  { name: "Overview" },
  { name: "All Contracts" },
  { name: "PDC Report" },
  { name: "Tenancy Details" },
  { name: "Tenancy Summery" },
  { name: "Move Out" },
  { name: "Maintenance" },
  { name: "Quotation" },
  { name: "Invoices" },
  { name: "Bookings" },
  { name: "Overview" },
  { name: "All Bookings" },
  { name: "Booking Details" },
  { name: "Booking Summery" },
  { name: "Sales" },
  { name: "Overview" },
  { name: "Sale Register" },
  { name: "All Expense" },
  { name: "Expense" },
  { name: "Purpose" },
  { name: "Service Charges" },
  { name: "Report And Insights" },
  { name: "PM Sheet" },
  { name: "Password Keeper" },
];

export default modules;
