const mockData = [
  {
    firstName: "Jack",
    lastName: "Abbasi",
    email: "jack.abbasi@example.com",
    jobTitle: "CEO",
    status: ["active", "pending"], 
    startDate: "2014-03-20T12:34:56",
    updateDate: "2019-06-11T10:20:30",
    createdByName: "Admin User",
    createdByEmail: "admin@example.com",
    updatedByName: "Super Admin",
    updatedByEmail: "superadmin@example.com",
    avatar: "https://i.pravatar.cc/150?img=6",
    address: "123 Main St, Cityville, Country",
    phoneNumber: "(123) 456-7890",
    department: "Executive",
    whatsAppNumber: "+971123456789",
    dateOfBirth: "1985-01-01",
    nationality: "Pakistani",
    passportIdNo: "AB1234567",
    passportIssueDate: "2015-01-01",
    passportExpiryDate: "2025-01-01",
    residentStatus: "Resident",
    passportPdf: "path/to/passport.pdf",
    emiratesIdAttachment: "path/to/emirates_id.pdf",
    nationalIdPdf: "path/to/national_id.pdf",
  },
  {
    firstName: "Rahima",
    lastName: "Khalid",
    email: "rahima.khalid@example.com",
    jobTitle: "Senior Property Consultant",
    status: "pending",
    startDate: "2018-06-11T15:30:00",
    updateDate: "2019-06-11T14:25:00",
    createdByName: "John Doe",
    createdByEmail: "john.doe@example.com",
    updatedByName: "Jane Smith",
    updatedByEmail: "jane.smith@example.com",
    avatar: "https://i.pravatar.cc/150?img=2",
    address: "456 Elm St, Townsville, Country",
    phoneNumber: "(987) 654-3210",
    department: "Consulting",
    whatsAppNumber: "+971234567890",
    dateOfBirth: "1988-04-15",
    nationality: "Emirati",
    passportIdNo: "XY9876543",
    passportIssueDate: "2018-02-15",
    passportExpiryDate: "2028-02-15",
    residentStatus: "Resident",
    passportPdf: "path/to/passport2.pdf",
    emiratesIdAttachment: "path/to/emirates_id2.pdf",
    nationalIdPdf: "path/to/national_id2.pdf",
  },
  {
    firstName: "Foster",
    lastName: "Willms",
    email: "foster.willms@example.com",
    jobTitle: "Lead Brand Assistant",
    status: "inactive",
    startDate: "2020-08-19T11:22:33",
    updateDate: "2021-06-11T09:00:00",
    createdByName: "David Lee",
    createdByEmail: "david.lee@example.com",
    updatedByName: "Michelle Kim",
    updatedByEmail: "michelle.kim@example.com",
    avatar: "https://i.pravatar.cc/150?img=3",
    address: "789 Oak St, Village, Country",
    phoneNumber: "(555) 678-9012",
    department: "Branding",
    whatsAppNumber: "+971345678901",
    dateOfBirth: "1992-07-20",
    nationality: "American",
    passportIdNo: "US1239874",
    passportIssueDate: "2020-05-20",
    passportExpiryDate: "2030-05-20",
    residentStatus: "Non-Resident",
    passportPdf: "path/to/passport3.pdf",
    emiratesIdAttachment: "path/to/emirates_id3.pdf",
    nationalIdPdf: "path/to/national_id3.pdf",
  },
];

export default mockData;
