const mockData = [
  {
    firstName: "Jack",
    lastName: "Abbasi",
    customerEmail: "jack.abbasi@example.com",
    customerMobileNo: "(123) 456-7890",
    otherCustomerName: "John Doe",
    otherCustomerEmail: "john.doe@example.com",
    otherCustomerMobileNo: "(555) 678-9012",
    poaTakerName: "Lawyer A",
    poaLanguage: "English",
    dateOfIssue: "2022-01-15",
    expiryDate: "2023-01-15",
    dateOfReValidation: "2022-06-01",
    reValidationExpiry: "2023-06-01",
    typeOfPoa: "General",
    nominated: "Yes",
    buying: "No",
    selling: "Yes",
    gifting: "No",
    renting: "No",
    management: "Yes",
    visa: "Yes",
    specificReason: "Legal Requirement",
    codePowerNo: "AB123",
    codePowerBranch: "Branch A",
    numberOfPoaOriginalWithUs: 2,
    poaDoneThruLawyerTypistSelf: "Lawyer",
    amountPaidCourtFees: 1000,
    amountPaidServiceFees: 500,
    attachment: "document.pdf",
    createdBy: "Admin",
    createdOn: "2024-01-01",
    updatedBy: "Admin",
    updatedOn: "2024-02-01",
  },
  {
    firstName: "Rahima",
    lastName: "Khalid",
    customerEmail: "rahima.khalid@example.com",
    customerMobileNo: "(987) 654-3210",
    otherCustomerName: "Jane Smith",
    otherCustomerEmail: "jane.smith@example.com",
    otherCustomerMobileNo: "(123) 456-7890",
    poaTakerName: "Lawyer B",
    poaLanguage: "Arabic",
    dateOfIssue: "2021-05-12",
    expiryDate: "2022-05-12",
    dateOfReValidation: "2021-12-01",
    reValidationExpiry: "2022-12-01",
    typeOfPoa: "Special",
    nominated: "No",
    buying: "Yes",
    selling: "No",
    gifting: "Yes",
    renting: "No",
    management: "No",
    visa: "No",
    specificReason: "Personal",
    codePowerNo: "CD456",
    codePowerBranch: "Branch B",
    numberOfPoaOriginalWithUs: 1,
    poaDoneThruLawyerTypistSelf: "Self",
    amountPaidCourtFees: 2000,
    amountPaidServiceFees: 1000,
    attachment: "document.png",
    createdBy: "John Doe",
    createdOn: "2024-02-01",
    updatedBy: "Jane Smith",
    updatedOn: "2024-03-01",
  },
  {
    firstName: "Foster",
    lastName: "Willms",
    customerEmail: "foster.willms@example.com",
    customerMobileNo: "(555) 678-9012",
    otherCustomerName: "Alice Johnson",
    otherCustomerEmail: "alice.johnson@example.com",
    otherCustomerMobileNo: "(555) 123-4567",
    poaTakerName: "Lawyer C",
    poaLanguage: "French",
    dateOfIssue: "2020-07-30",
    expiryDate: "2021-07-30",
    dateOfReValidation: "2020-12-01",
    reValidationExpiry: "2021-12-01",
    typeOfPoa: "Durable",
    nominated: "Yes",
    buying: "No",
    selling: "Yes",
    gifting: "No",
    renting: "Yes",
    management: "Yes",
    visa: "No",
    specificReason: "Legal Compliance",
    codePowerNo: "EF789",
    codePowerBranch: "Branch C",
    numberOfPoaOriginalWithUs: 3,
    poaDoneThruLawyerTypistSelf: "Typist",
    amountPaidCourtFees: 1500,
    amountPaidServiceFees: 750,
    attachment: "document.jpg",
    createdBy: "David Lee",
    createdOn: "2024-03-01",
    updatedBy: "Michelle Kim",
    updatedOn: "2024-04-01",
  },
];

export default mockData;
